### ISSUE TITLE
Normalise handling of email addresses

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/models#108]
**Is your feature request related to a problem? Please describe.**
`User` emails are [currently stripped and downcased](https://github.com/PlaceOS/models/blob/9426c230842bb1aadfda51d861da89e511f050bd/src/placeos-models/user.cr#L91) when validating for uniqueness but persisted with case and surrounding whitespace preserved. This same normalisation is not applied elsewhere resulting in unexpected behaviour in other areas of the system.

An externally visible example of this is the [`rest-api` users controller](https://github.com/PlaceOS/rest-api/blob/master/src/placeos-rest-api/controllers/users.cr) where interactions based on user email require a case matched version to be used.

**Describe the solution you'd like**
Perform consistent validation and matching of email address across all areas of the platform.

**Describe alternatives you've considered**
Performing ad-hoc normalisation either client side, or in other services. Centralising this here appears to be the least error prone approach

**Additional context**
- To conform with [`rfc5321`](https://datatracker.ietf.org/doc/html/rfc5321#section-2.4) case of the address MUST be preserved for usage in actual emails.
- Some additional complexity also exists for how [`email_digest`](https://github.com/PlaceOS/models/blob/9426c230842bb1aadfda51d861da89e511f050bd/src/placeos-models/user.cr#L33) should be handled.
- Approach used in resolving this issue should also be matched in the [`auth` user](https://github.com/PlaceOS/auth/blob/master/app/models/user.rb) and [`staff-api` guest](https://github.com/PlaceOS/staff-api/blob/master/src/models/guest.cr) models.

**Comment by caspiano** [comment]
Shall we define a simple `Email` struct? 

```crystal
struct Email
  getter address : String
  delegate to_json, to: address

  def initialize(address : String)
    raise "Invalid email" unless address.is_email?
    @address = address
  end
  
  def self.from_json(pull)
    new pull.read_string
  end
  
  def digest
    # generate a SHA-1 digest of the email
  end
end
```

**Comment by caspiano** [comment]
Related https://github.com/spider-gazelle/rethinkdb-orm/issues/29
