### ISSUE TITLE
Rename `Authority` to `Domain`

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/models#146]
**Is your feature request related to a problem? Please describe.**

`Authority` is a confusing term, where `Domain` is more reflective of the function of the models.

**Describe the solution you'd like**

Rename `Authority` to `Domain`

**Additional context**

This could be done during the migration to postgres in #71

Alternatively, a migration script could be written for RethinkDB.

**Comment by jeremyw24** [comment]
@stakach advised to close.
