### ISSUE TITLE
Update CI schedule to fix notifications

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/models#184]
Hello! 
Since I set the schedule of the CI job, I receive notifications every time the job runs.
If a Place employee could update [this line](https://github.com/PlaceOS/models/blob/cba775d85204b58153ca58994710f73ee847c297/.github/workflows/ci.yml#L5
), that would be very appreciated. 
Thanks!

**Comment by camreeves** [comment]
Done. Thanks for letting us know!

**Comment by caspiano** [comment]
@stakach @camreeves I'm still getting these.

**Comment by caspiano** [comment]
Bump @stakach
