### ISSUE TITLE
Support repository branches

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/models#26]
Currently, master is the only functional branch when referenced by a `PlaceOS::Model::Repository`.

A simple `branch : String = "master"` attribute will suffice.

**Comment by stakach** [comment]
agreed, let's not bother with an API to grab the list of branches.
we can default it to master and if anyone wants to edit it, it's at their own risk

**Comment by MrYuion** [comment]
I've added support for this in backoffice.
